services:
  app:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ../../demo:/var/www/project/demo
      # - ./97-memcached.ini:${PHP_INI_DIR}/97-memcached.ini
      - ./${XDEBUG_CONFIG_FILE:-98-xdebug.ini}:${PHP_INI_DIR}/98-xdebug.ini
      - ./99-custom-php-conf.ini:${PHP_INI_DIR}/99-custom-php-conf.ini
      - ./apache_default.conf:${APACHE_CONF_DIR}/000-default.conf
    restart: ${RESTART_POLICY:-no}
    env_file:
      - ../../.env
    extra_hosts: # to enable access to host machine from within the container (access databases, etc)
      - "host.docker.internal:host-gateway"